# docker-compose.yml
# This file defines the services for our application, in this case, MongoDB.
# Using Docker Compose allows us to run multi-container Docker applications.

version: '3.8' # Specifies the version of the Docker Compose file format.

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333" # API port
      - "6334:6334" # gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage # Persist data

  app:
    build: .
    container_name: travel_agent_app
    depends_on:
      - qdrant
    env_file:
      - .env
    volumes:
      - ./src:/app/src