name: llmagent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter>=1.0.0
  - ipykernel>=6.29.0
  - pip
  - pip:
      - langchain>=0.3.0
      - langchain-openai>=0.2.0
      - python-dotenv>=1.0.0
      - huggingface_hub>=0.24.0
      - googlesearch-results>=2.4.2
      - faiss-cpu>=1.8.0
      - tiktoken>=0.7.0