# -*- coding: utf-8 -*-
"""Supervised Fine Tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7iYraPDJb9HGvzMWcJ_Av04OzC_Yc2z
"""

#@title 1. Install Necessary Libraries
# We'll start by installing all the libraries we need.
# Unsloth will handle the heavy lifting of making the model run fast and efficiently.
# Transformers, peft, accelerate, and trl are all libraries from Hugging Face
# that help with loading models, applying efficient tuning techniques (like LoRA),
# and running the training process.
# --- FIX: Simplified and updated installation commands ---
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install "peft" "accelerate" "bitsandbytes" "trl"
# --- ADDED: Install comet_ml for experiment tracking, specifying the required version ---
!pip install "comet_ml>=3.43.2"

#@title 2. Load the Model and Tokenizer
import torch
from unsloth import FastLanguageModel

# Let's define some key parameters
max_seq_length = 2048 # This is the maximum number of words the model can handle in a single input.
dtype = None # We'll let unsloth decide the best data type.
load_in_4bit = True # This is the magic! Loading in 4-bit drastically reduces memory usage.

# Here, we load our Mistral model using Unsloth's FastLanguageModel.
# This function automatically downloads the model, applies massive speed-ups,
# and prepares it for fine-tuning.
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/mistral-7b-instruct-v0.2-bnb-4bit", # This is a pre-quantized Mistral model, perfect for Colab.
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

#@title 3. Prepare the Model for Fine-Tuning with LoRA
# Now, we need to prepare the model for training.
# We're using a technique called LoRA (Low-Rank Adaptation).
# Think of it like this: instead of training the entire, massive model (which would take too long and too much memory),
# we add tiny, trainable "adapter" layers. We only train these small adapters,
# which is much more efficient. Unsloth makes this incredibly simple.

model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # This is a key LoRA parameter. Common values are 8, 16, 32. Higher means more trainable parameters.
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",], # These are the specific layers in the model we'll attach our adapters to.
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = True, # This is a memory-saving technique.
    random_state = 42,
    use_rslora = False,
    loftq_config = None,
)

#@title 4. Prepare the Instruction Dataset
# This is the most important step. We need to teach the model our specific task.
# The IMDB dataset just has a 'text' (the review) and a 'label' (0 for negative, 1 for positive).
# We need to convert this into an "instruction" format that the model can understand.
# We will format it like a question and answer.

from datasets import load_dataset

# This is the instruction template we'll use.
# It clearly tells the model what to do: "Classify the sentiment..."
# The `### Review:` and `### Sentiment:` sections provide clear structure.
instruction_prompt = """Classify the sentiment of this movie review. Is it positive or negative?

### Review:
{}

### Sentiment:
{}"""

# This function will take a single example from the IMDB dataset
# and format it into our instruction prompt.
def format_row_for_instruction(row):
    # Convert the label (0 or 1) into a human-readable word ("Negative" or "Positive")
    sentiment = "Positive" if row["label"] == 1 else "Negative"
    # Fill in the template with the review text and the sentiment
    formatted_text = instruction_prompt.format(row["text"], sentiment)
    return {"text": formatted_text}

# Load the IMDB dataset from Hugging Face
dataset = load_dataset("imdb", split="train")

# Now, we apply our formatting function to the entire dataset.
# The .map() function is a very efficient way to do this.
dataset = dataset.map(format_row_for_instruction)

# Let's look at one example to see what our formatted data looks like.
print("--- Example of a Formatted Data Row ---")
print(dataset[0]['text'])

#@title 5. Fine-Tune the Model with the SFTTrainer
from trl import SFTTrainer
from transformers import TrainingArguments
import os
from google.colab import userdata

# --- ADDED: Set up Comet ML environment variables from Colab Secrets ---
os.environ["COMET_API_KEY"] = userdata.get('COMET_API_KEY')
os.environ["COMET_PROJECT_NAME"] = userdata.get('COMET_PROJECT_NAME')
os.environ["COMET_WORKSPACE"] = userdata.get('COMET_WORKSPACE')


# The SFTTrainer (Supervised Fine-Tuning Trainer) is a convenient tool
# from the TRL library that handles the entire training loop for us.

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text", # We tell the trainer to use the 'text' column of our formatted dataset.
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False, # Can make training faster, but we'll keep it simple for now.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4, # These two combined give an effective batch size of 8.
        warmup_steps = 5,
        # --- FIX: Increased training steps for better model performance ---
        max_steps = 120, # Increased from 60. More steps help the model learn better.
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 42,
        output_dir = "outputs", # Where to save training outputs.
        # --- ADDED: Tell the trainer to log to Comet ML ---
        report_to = "comet_ml",
    ),
)

# Let's start the training!
print("--- Starting the Fine-Tuning Process ---")
trainer_stats = trainer.train()
print("--- Fine-Tuning Finished! ---")

#@title 6. Test the Fine-Tuned Model (Inference)
# The training is done, but how do we know if it worked?
# We need to ask our newly fine-tuned model to classify some reviews it has never seen before.
from transformers import TextStreamer

# We need to re-load the base model and tokenizer for inference.
FastLanguageModel.for_inference(model) # This prepares the model for fast predictions.

tokenizer.pad_token = tokenizer.eos_token

# Let's create a couple of test reviews.
review_1 = "This movie was an absolute masterpiece. The acting was superb, the plot was gripping, and the ending was perfect. I was on the edge of my seat the entire time. A must-see!"
review_2 = "What a waste of time. The plot was nonsensical, the characters were flat, and I couldn't wait for it to be over. I would not recommend this to anyone."

# --- FIX: Use a more standard two-step process for preparing the inputs ---
# 1. Format the prompt using the chat template
messages_1 = [
    {"role": "user", "content": f"Classify the sentiment of this movie review. Is it positive or negative?\n\n### Review:\n{review_1}"},
]
prompt_1 = tokenizer.apply_chat_template(messages_1, tokenize = False, add_generation_prompt = True)

messages_2 = [
    {"role": "user", "content": f"Classify the sentiment of this movie review. Is it positive or negative?\n\n### Review:\n{review_2}"},
]
prompt_2 = tokenizer.apply_chat_template(messages_2, tokenize = False, add_generation_prompt = True)


# 2. Tokenize the formatted prompts to get a dictionary of tensors
inputs_1 = tokenizer(prompt_1, return_tensors = "pt").to("cuda")
inputs_2 = tokenizer(prompt_2, return_tensors = "pt").to("cuda")

# Now, let's get the model's predictions.
# --- FIX: Added more robust sampling parameters and explicit stop token ---
outputs_1 = model.generate(
    **inputs_1,
    max_new_tokens = 10,
    do_sample = True,
    temperature = 0.7,
    top_k = 50,
    top_p = 0.95,
    repetition_penalty = 1.1,
    eos_token_id=tokenizer.eos_token_id,
)
decoded_output_1 = tokenizer.decode(outputs_1[0][len(inputs_1['input_ids'][0]):], skip_special_tokens=True)
print("--- Review 1 (Expected: Positive) ---")
print(f"Model Output: '{decoded_output_1.strip()}'")
print("\n" + "="*50 + "\n")


outputs_2 = model.generate(
    **inputs_2,
    max_new_tokens = 10,
    do_sample = True,
    temperature = 0.7,
    top_k = 50,
    top_p = 0.95,
    repetition_penalty = 1.1,
    eos_token_id=tokenizer.eos_token_id,
)
decoded_output_2 = tokenizer.decode(outputs_2[0][len(inputs_2['input_ids'][0]):], skip_special_tokens=True)
print("--- Review 2 (Expected: Negative) ---")
print(f"Model Output: '{decoded_output_2.strip()}'")

# You should now see the model output "### Sentiment: Positive" and "### Sentiment: Negative"